apps:
- name: leilao-centavos-back-end
  cwd: ./back-end
  script: npm
  args: "start"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  watch: true
  env:
    PORT: 3001
- name: leilao-centavos-front-end
  cwd: ./front-end
  script: npm
  args: "start"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  watch: true
  env:
    PORT: 3000
